= Сетевой уровень

Технологии канального уровня позволяют нам создать сегмент сети и обмениваться в нем данными между хостами. Для идентификации хостов используются MAC адреса. Для объединения сегментов сетей используется сетевой уровень модели OSI.

Напомню, что сетевой уровень отвечает за доставку данных между хостами. При этом не важно, находятся эти хосты в одном сетевом сегменте, в соседних или между ними 10 000 км.

Если вы вдруг попытаетесь решить эту задачу на канальном уровне, то у вас возникнут большие проблемы. В частности, на какой адрес отправлять пакет? В Ethernet сетях MAC адрес размером в 6 байт (48 бит), а в других технологиях канального уровня он может быть меньше или больше.

Поэтому, для решения проблемы объединения сетей необходимо подняться выше канального уровня, т.е. на сетевой.

Сетевой уровень - это первый полностью программный уровень в модели OSI. Другими словами, он полностью не зависит от оборудования. Один и тот же сетевой уровень может успешно работать на проводном Ethernet, на Wi-FI, в 3G сетях и так далее.
