= Многопоточный TCP-сервер

Однопоточный TCP-сервер хорош только для примера. В реальности, конечно, TCP-сервер всегда многопоточный и готов одновременно обслуживать несколько клиентов. Разберем несколько способов создания многопточного TCP-сервера.

== Многопоточный TCP-сервер (fork)

В основе многопоточного TCP-сервера на fork лежит вызов функции ``fork()``. ``Fork()`` - это системный вызов в UNIX-подобных ОС (в ОС windows он эмулируется). Вызова ``fork()`` создает в ОС идентичиный (полная копия процесса, включая состояния регистров процессора, открытых дескрипторов, памяти и фгалов) процесс (child/ребенок), который начинает свое выполнение со следующей команды сразу после ``fork``.

NOTE: Более подробно про ``fork()`` - https://man7.org/linux/man-pages/man2/fork.2.html

Общая идея работы многопоточного сервера через fork() такая:

* Родительский процесс работает с серверным сокетом и ожидает подключения новых клиентов
* При подключении клиента родительский процесс создает дочерний процесс
* Дочерний процесс занимается обслуживанием клиента, а родительский, в это время, ожидает подключения нового клиента.

Ниже представлен пример многопоточного TCP эхо-сервера с использованием fork().

[source,python]
----
#!/usr/bin/python

import socket
import os
import sys
import signal

HOST = 'localhost'
PORT = 30001
data_payload = 2048
backlog = 5

def sigchld_handler(*args):
    pid, exit_code = os.wait()
    print ("Child pid %d exiting with code %d" % (pid, exit_code//256))

def client_handler(client):

    while True:
        data = client.recv(data_payload)

        if not data:
            break

        print("Data: %s" % data)
        s = client.send(data)
        print("sent %s bytes back" % (s,))

    # End connection
    client.close()


signal.signal(signal.SIGCHLD, sigchld_handler)

# Create a TCP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Enable reuse address/port
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

print("Starting up echo server on %s port %s" % (HOST, PORT))
sock.bind((HOST, PORT))

# Listen to clients, backlog argument specifies the max no. of queued connections
sock.listen(backlog)

while True:
    print("Waiting to receive message from client")
    client, address = sock.accept()
    print("Client connected from %s" % (address,))

    # Create new child
    p = os.fork()

    # We're child?
    if not p:
        client_handler(client)

        # Exit from child
        # Don't go to while True!
        sys.exit(1)
----

Запустим этот TCP эхо-сервер и проверим, на сколько он справляется с задачей. После запуска сервера он сообщит о готовности к работе, как показано ниже.

[source,console]
----
(venv) ScrumBook:src ilya2$ python tcp-server-1-fork.py
Starting up echo server on localhost port 30001
Waiting to receive message from client
----

Поочередно запустите утилиту ``nc localhost 30001`` из двух консолей. И попробуйте отправлять строки из первой и из второй консоли. У меня получается это сделать без проблем и задержек. Другими словами, TCP-сервер успешно обслуживает двух клиентов. Можете запустить еще несколько консолей, он успешно справится с десятками подобных запросов.

[source,console]
----
ScrumBook:~ ilya2$ nc localhost 30001
Hello TCP-server with fork
Hello TCP-server with fork
----

А теперь давайте разберемся, как все это работает.

NOTE: Считается, что вы уже понимаете основные моменты в работе TCP-сервера и разбор примера будет касаться только многопоточной реализации.

[source,python]
----
def sigchld_handler(*args):
    pid, exit_code = os.wait()
    print ("Child pid %d exiting with code %d" % (pid, exit_code//256))
----

Функция ``sigchld_handler`` - обработчик сигнала SIGCHLD. Когда наша программа вызовет функцию fork(), то в системе появится идентичный процесс. Этот новый процесс называют дочерний, а тот кто его породил - родительский. Во время завершения работы дочерний процесс сообщает родительскому свой код возврата (статус выхода). Этот код возврата будет находиться в памяти ОС до тех пор, пока родительский процесс его не прочитает. Чтобы родительский процесс понял, что один из его детей завершил свою работу, система посылает родительскому процессу сигнал CHILD (SIGCHLD).

Другими словами, при завершении дочернего процесса ОС отправляет родительскому процессу сигнал SIGCHLD и держит в памяти код возврата ребенка.

По умолчанию, у сигнала SIGCHLD стоит пустой обработчик и родительский процесс  ничего не делает при его получении. Поэтому, мы поменяем обработчик сигнала SIGCHLD на свой.

[source,python]
----
signal.signal(signal.SIGCHLD, sigchld_handler)
----

Наша функция ``sigchld_handler`` вызывает функцию ``os.wait``, которая вернет идентификатор завершившегося дочернего процесса (pid) и его код возврата (exit_code).

[source,python]
----
def client_handler(client):

    while True:
        data = client.recv(data_payload)

        if not data:
            break

        print("Data: %s" % data)
        s = client.send(data)
        print("sent %s bytes back" % (s,))

    # End connection
    client.close()
----

Функция ``client_handler`` будет заниматься обработкой клиента.

[source,python]
----
data = client.recv(data_payload)
----

В ней мы в вечном цикле ожидаем данных от клиента. Если данные пришли, отправляем их клиенту обратно и снова ждем данные от клиента. Очень простой эхо-сервер.

[source,python]
----
s = client.send(data)
----

Если клиент закроет соединение, то функция ``recv`` вернет пустое значение, мы выйдем из вечного цикла, закроем клиентское соединение со своей стороны и выйдем из функции.

[source,python]
----
    # Create new child
    p = os.fork()

    # We're child?
    if not p:
        client_handler(client)

        # Exit from child
        # Don't go to while True!
        sys.exit(1)
----

А это основной код родительского процесса. Функция ``fork`` создает дочерний процесс и начинает его выполнение со следующей команды после вызова ``fork``. Чтобы понять, где-кто, функция ``fork`` вернет родителю идентификатор (pid) ребенка, а ребенку 0.

Поэтому, если мы родитель, то пропускаем всю работу с клиентским сокетом и возвращаемся в функцию ``accept``. Если мы ребенок, то вызываем функцию для работы с клиентом ``client_handler``. По её завершению завершаем и весь наш дочерний процесс (``sys.exit(1)``).

Используя функцию ``fork`` можно очень просто реализовать многопоточный сервер.

=== Зомби-процессы

Если разработчик забудет или неверно реализует обработку сигнала SIGCHLD, то это приводит к появлению в системе так называемых зомби-процессов. Зомби-процесс - это завершившийся дочерний процесс, чей код возврата еще никто не прочитал. Зомби его называют потому, что он уже закончил работу и больше ничего делать не будет (по сути мертвый), но занимает pid и числится в списке процессов.

Давайте проведем небольшой эксперимент. Закомментируем строку с регистрацией нашего обработчика сигнала SIGCHLD.

[source,python]
----
#signal.signal(signal.SIGCHLD, sigchld_handler)
----

Запустим наш эхо-сервер, несколько раз подключимся к нему утилитой ``netcat`` и отправим 1-2 строки (не важно сколько строк, главное, подключиться и отключиться, чтобы был создан дочерний процесс).

[source,console]
----
ScrumBook:~ ilya2$ nc localhost 30001
Hello TCP-server with fork
Hello TCP-server with fork
^C
ScrumBook:~ ilya2$ nc localhost 30001
Hello
Hello
^C
ScrumBook:~ ilya2$ nc localhost 30001
Privet
Privet
^C
ScrumBook:~ ilya2$ nc localhost 30001
Hi, my name is...
Hi, my name is...
^C
ScrumBook:~ ilya2$ nc localhost 30001
----

А теперь посмотрим на список процессов.

NOTE: Если у вас ОС Linux, то это можно сделать с помощью команды ``ps`` с флагами axf (``ps axf``). Под MacOS лучше установить утилиту ``pstree`` через ``brew`` (``brwe install pstree``).

[source,console]
----
|   \-+= 49798 ilya2 /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python tcp-server-1-fork-zombie.py
 |     |--- 49810 ilya2 (Python)
 |     |--- 49812 ilya2 (Python)
 |     |--- 49815 ilya2 (Python)
 |     \--- 52502 ilya2 (Python)
----

Как видно, у родительского процесса tcp-server-1-fork-zombie.py висит 4 дочерних процесса. Если посмотреть статусы этих процессов, то видно, что все дочерние процессы в состоянии Z+ (из документации по утилите ps "Marks a dead process (a 'zombie')")

[source,console]
----
49798 s000  S+     0:00.09 /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python tcp-server-1-fork-zombie.py
49810 s000  Z+     0:00.00 (Python)
49812 s000  Z+     0:00.00 (Python)
49815 s000  Z+     0:00.00 (Python)
52502 s000  Z+     0:00.00 (Python)
----

NOTE: Так как я запускаю все примеры на MacOS, то для просмотра статуса процесса мне приходится использовать утилиту ``ps``. А для рисования древовидной структуры ``pstree``. В ОС Linux утилита ``ps`` умеет рисовать древовидную структуру процессов и отображать их статусы сразу.

В процессе работы такого сервера в системе будут множиться зомби процессы. Лучше этого не допускать. А для этого не забывайте про сигнал SIGCHLD.

=== Межпроцессное взаимодейтсвие

Функция ``fork`` создает отдельный процесс. Если во время работы вам потребуется обмениваться данными между обработчиками клиентов или между дочерним и родительским процессом, то вам придется использовать что-то для межпроцессного взаимодействия (пайп, сокет, файл, БД).

== Многопоточный TCP-сервер (threads/потоки/нити)

В основе многопоточного сервера на потоках (threads) лежит возможность запускать несколько потоков исполнения кода в рамках одного процесса. Ниже представлен наш TCP эхо-сервер на потоках.

[source,python]
----
#!/usr/bin/python

import socket
import threading

HOST = 'localhost'
PORT = 30002
data_payload = 2048
backlog = 5

def client_handler(client):

    while True:
        data = client.recv(data_payload)

        if not data:
            break

        print("Data: %s" % data)
        s = client.send(data)
        print("sent %s bytes back" % (s,))

    # End connection
    client.close()

# Create a TCP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Enable reuse address/port
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

print("Starting up echo server on %s port %s" % (HOST, PORT))
sock.bind((HOST, PORT))

# Listen to clients, backlog argument specifies the max no. of queued connections
sock.listen(backlog)

while True:
    print("Waiting to receive message from client")
    client, address = sock.accept()
    print("Client connected from %s" % (address,))

    # Create and start thread
    t = threading.Thread(target=client_handler, args=(client,))
    t.start()

----

Запустим этот TCP эхо-сервер и проверим его работоспособность. После запуска, как обычно, подключимся к нему из нескольких консоль и убедимся, что эхо-сервер способен обрабатывать несколько клиентов одновременно.

А когда вы все проверили, давайте разбираться, как все работает.

[source,python]
----
#!/usr/bin/python

import socket
import threading
----

Для работы с потоками в Python используется модуль threading.

[source,python]
----
def client_handler(client):

    while True:
        data = client.recv(data_payload)

        if not data:
            break

        print("Data: %s" % data)
        s = client.send(data)
        print("sent %s bytes back" % (s,))

    # End connection
    client.close()
----

Наша функция ``client_handler`` для работы с клиентом. В начале она ожидает ввод от клиента. Если данные от клиента пришли, то она отправляет их ему обратно и снова начинает ждать данные от клиента. И так по кругу. А если функция ``recv`` вернулась без данных, значит соединение было закрыто и можно завершать работу. Вызываем функцию ``close`` и выходим из обработчика потока.

[source,python]
----
while True:
    print("Waiting to receive message from client")
    client, address = sock.accept()
    print("Client connected from %s" % (address,))

    # Create and start thread
    t = threading.Thread(target=client_handler, args=(client,))
    t.start()
----

Главный поток ожидает подключения нового клиента (``accept``). Когда клиент подключился, формирует новый поток и запускает его (``t.start()``).

В целом, это все!

NOTE: При работе с потоками важно помнить про Global Interpreter Lock (GIL).

Такая реализация чуть попроще, чем через ``fork()``, так как нет нужды обрабатывать SIGCHLD.

Реализации через fork и потоки имют свои достоинства и недостатки. Например, реализация многопоточной работы на потоках позволяет использовать общую память и обмениваться данными между потоками. С другой стороны, из-за GIL все потоки реально будут исполняться поочереди.

== Многопоточный TCP-сервер (потоки и select)

