== TCP-сервер

Отличительной особенностью реализации сервера является открытие так называемого серверного сокета. Общая идея такая:

* открываем обыкновенный сокет
* переводим сокет в режим ожидания соединения
* при подключении клиента создается сокет для работы с клиентом, его еще называют клиентский сокет
* выполняем обычную работу с клиентским сокетом.




Давайте напишем первого сетевого клиента, который будет подключаться к серверу miminet.ru на порт 80 (TCP) и отправлять простой HTTP-запрос.

NOTE: HTTP (HyperText Transfer Protocol) - протокол для коммуникации с веб-сервером. HTTP-запрос - запрос отправляемый клиентом на веб-сервер. В ответ на такой запрос веб-сервер отправляет данные (HTML страницу, JS код, картинки, видео и т.д.) или отправляет информационное сообщение.

NOTE: По умолчанию, веб-сервер для работы использует порт 80 (TCP).

Нам необходимо выполнить следующие действия:

. Создать TCP сокет.
. Подключиться к веб-серверу miminet.ru на порт 80.
. Отправить HTTP-запрос.
. Получить ответ и вывести его на экран.

[source,python]
----
#!/usr/bin/python

import socket

HOST = "miminet.ru"
PORT = 80                                               # HTTP port

ip_addr = socket.gethostbyname(HOST)                    # Get IP address by name
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)   # Create TCP socket
s.connect((ip_addr, PORT))                              # Connect to miminet.ru
s.send(b'GET / HTTP/1.0\n\n')                           # Send HTTP-request
data = s.recv(4096)                                     # Recieve data from miminet.ru
print(data)                                             # Print data to console

----

Вы можете скопировать этот код и попробовать выполнить его у себя. В результате его работы в консоль должно вывестись следующее сообщение:

[source]
----
(venv) ScrumBook:src ilya2$ python tcp-client-1.py
b'HTTP/1.1 301 Moved Permanently\r\nServer: nginx/1.25.4\r\nDate: Wed, 16 Oct 2024 08:40:37 GMT\r\nContent-Type: text/html\r\nContent-Length: 169\r\nConnection: close\r\nLocation: https://miminet.ru/\r\n\r\n<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body>\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx/1.25.4</center>\r\n</body>\r\n</html>\r\n'
----

Я постарался прокомментировать каждую строку, но давайте подробней  разберем, что мы делаем и что происходит

[source,python]
----
import socket
----
